name: Generate Micro SDK
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.body, 'APP:') || contains(github.event.pull_request.body, 'app:')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm init -y 2>/dev/null || true
          npm install axios dotenv
      
      - name: Create sdks directory
        run: |
          mkdir -p sdks
          mkdir -p scripts
      
      - name: Create dummy generate-sdk.js (temporary)
        run: |
          cat > scripts/generate-sdk.js << 'EOF'
          console.log("PR Body:", process.env.PR_BODY);
          console.log("PR Number:", process.env.PR_NUMBER);
          console.log("Generating SDK...");
          
          // Create a dummy SDK file for testing
          const fs = require('fs');
          fs.writeFileSync('sdks/test-sdk.js', 'console.log("Generated SDK!");');
          console.log("SDK generated successfully!");
          EOF
      
      - name: Generate SDK
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: node scripts/generate-sdk.js

# ... previous steps ...

      - name: Commit generated SDK
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add sdks/
            git commit -m "🤖 Auto-generate SDK for PR #${{ github.event.pull_request.number }}"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No SDK files to commit"
          fi
        
