# .github/workflows/generate-sdk.yml
name: Generate Micro SDK

on:
  pull_request:
    types: [opened, edited, synchronize]
    # Only trigger if PR contains SDK generation request
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    
    # Only run if PR body contains app specification
    if: contains(github.event.pull_request.body, 'APP:') || contains(github.event.pull_request.body, 'app:')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm init -y 2>/dev/null || true
          npm install axios dotenv
      
      - name: Create directories
        run: |
          mkdir -p sdks
          mkdir -p scripts
      
      - name: Generate SDK
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: node scripts/generate-sdk.js
      
    
