name: Generate Micro SDK
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "PR Body: ${{ github.event.pull_request.body }}"
          echo "Contains APP: ${{ contains(github.event.pull_request.body, 'APP:') }}"
