name: Generate Micro SDK
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.body, 'APP:') || contains(github.event.pull_request.body, 'app:')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm init -y 2>/dev/null || true
          npm install axios dotenv
      
      - name: Create sdks directory
        run: |
          mkdir -p sdks
          mkdir -p scripts
      
      - name: Test directories
        run: |
          echo "Directories created successfully!"
          ls -la
